version: '3'

services:
  app:
    container_name: "tinkoff-translator-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - YANDEX_TOKEN=
      - YANDEX_FOLDERID=
