yandex:
  token:
  folderId:

spring:
#  datasource:
#    url: jdbc:h2:mem:translator-api
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

server:
  port: 8081